# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

<<<<<<< HEAD
# Disable implicit rules so canonical targets will work.
.SUFFIXES:
=======
CPPFLAGS	+= -I./include -Wall -std=gnu++1z -I/usr/include/irrlicht/ -lIrrlicht -lpthread -pthread -lstdc++fs -lIrrKlang -Wfatal-errors
>>>>>>> 8014bcd1977f805ea5b0a582508ca9b9f0fe41d6


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Stan/home/Projects/cpp/BomberMan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Stan/home/Projects/cpp/BomberMan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Stan/home/Projects/cpp/BomberMan/CMakeFiles /mnt/c/Users/Stan/home/Projects/cpp/BomberMan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Stan/home/Projects/cpp/BomberMan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

Game/ACube.o: Game/ACube.cpp.o

.PHONY : Game/ACube.o

# target to build an object file
Game/ACube.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/ACube.cpp.o
.PHONY : Game/ACube.cpp.o

Game/ACube.i: Game/ACube.cpp.i

.PHONY : Game/ACube.i

# target to preprocess a source file
Game/ACube.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/ACube.cpp.i
.PHONY : Game/ACube.cpp.i

Game/ACube.s: Game/ACube.cpp.s

.PHONY : Game/ACube.s

# target to generate assembly for a file
Game/ACube.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/ACube.cpp.s
.PHONY : Game/ACube.cpp.s

Game/Bomb.o: Game/Bomb.cpp.o

.PHONY : Game/Bomb.o

# target to build an object file
Game/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Bomb.cpp.o
.PHONY : Game/Bomb.cpp.o

Game/Bomb.i: Game/Bomb.cpp.i

.PHONY : Game/Bomb.i

# target to preprocess a source file
Game/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Bomb.cpp.i
.PHONY : Game/Bomb.cpp.i

Game/Bomb.s: Game/Bomb.cpp.s

.PHONY : Game/Bomb.s

# target to generate assembly for a file
Game/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Bomb.cpp.s
.PHONY : Game/Bomb.cpp.s

Game/Crate.o: Game/Crate.cpp.o

.PHONY : Game/Crate.o

# target to build an object file
Game/Crate.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Crate.cpp.o
.PHONY : Game/Crate.cpp.o

Game/Crate.i: Game/Crate.cpp.i

.PHONY : Game/Crate.i

# target to preprocess a source file
Game/Crate.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Crate.cpp.i
.PHONY : Game/Crate.cpp.i

Game/Crate.s: Game/Crate.cpp.s

.PHONY : Game/Crate.s

# target to generate assembly for a file
Game/Crate.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Crate.cpp.s
.PHONY : Game/Crate.cpp.s

Game/EntityPos.o: Game/EntityPos.cpp.o

.PHONY : Game/EntityPos.o

# target to build an object file
Game/EntityPos.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/EntityPos.cpp.o
.PHONY : Game/EntityPos.cpp.o

Game/EntityPos.i: Game/EntityPos.cpp.i

.PHONY : Game/EntityPos.i

# target to preprocess a source file
Game/EntityPos.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/EntityPos.cpp.i
.PHONY : Game/EntityPos.cpp.i

Game/EntityPos.s: Game/EntityPos.cpp.s

.PHONY : Game/EntityPos.s

# target to generate assembly for a file
Game/EntityPos.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/EntityPos.cpp.s
.PHONY : Game/EntityPos.cpp.s

Game/Fire.o: Game/Fire.cpp.o

.PHONY : Game/Fire.o

# target to build an object file
Game/Fire.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Fire.cpp.o
.PHONY : Game/Fire.cpp.o

Game/Fire.i: Game/Fire.cpp.i

.PHONY : Game/Fire.i

# target to preprocess a source file
Game/Fire.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Fire.cpp.i
.PHONY : Game/Fire.cpp.i

Game/Fire.s: Game/Fire.cpp.s

.PHONY : Game/Fire.s

# target to generate assembly for a file
Game/Fire.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Fire.cpp.s
.PHONY : Game/Fire.cpp.s

Game/GameCore.o: Game/GameCore.cpp.o

.PHONY : Game/GameCore.o

# target to build an object file
Game/GameCore.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/GameCore.cpp.o
.PHONY : Game/GameCore.cpp.o

Game/GameCore.i: Game/GameCore.cpp.i

.PHONY : Game/GameCore.i

# target to preprocess a source file
Game/GameCore.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/GameCore.cpp.i
.PHONY : Game/GameCore.cpp.i

Game/GameCore.s: Game/GameCore.cpp.s

.PHONY : Game/GameCore.s

# target to generate assembly for a file
Game/GameCore.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/GameCore.cpp.s
.PHONY : Game/GameCore.cpp.s

Game/Item.o: Game/Item.cpp.o

.PHONY : Game/Item.o

# target to build an object file
Game/Item.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Item.cpp.o
.PHONY : Game/Item.cpp.o

Game/Item.i: Game/Item.cpp.i

.PHONY : Game/Item.i

# target to preprocess a source file
Game/Item.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Item.cpp.i
.PHONY : Game/Item.cpp.i

Game/Item.s: Game/Item.cpp.s

.PHONY : Game/Item.s

# target to generate assembly for a file
Game/Item.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Item.cpp.s
.PHONY : Game/Item.cpp.s

Game/Player.o: Game/Player.cpp.o

.PHONY : Game/Player.o

# target to build an object file
Game/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Player.cpp.o
.PHONY : Game/Player.cpp.o

Game/Player.i: Game/Player.cpp.i

.PHONY : Game/Player.i

# target to preprocess a source file
Game/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Player.cpp.i
.PHONY : Game/Player.cpp.i

Game/Player.s: Game/Player.cpp.s

.PHONY : Game/Player.s

# target to generate assembly for a file
Game/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Player.cpp.s
.PHONY : Game/Player.cpp.s

Game/Shield.o: Game/Shield.cpp.o

.PHONY : Game/Shield.o

# target to build an object file
Game/Shield.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Shield.cpp.o
.PHONY : Game/Shield.cpp.o

Game/Shield.i: Game/Shield.cpp.i

.PHONY : Game/Shield.i

# target to preprocess a source file
Game/Shield.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Shield.cpp.i
.PHONY : Game/Shield.cpp.i

Game/Shield.s: Game/Shield.cpp.s

.PHONY : Game/Shield.s

# target to generate assembly for a file
Game/Shield.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Shield.cpp.s
.PHONY : Game/Shield.cpp.s

Game/Wall.o: Game/Wall.cpp.o

.PHONY : Game/Wall.o

# target to build an object file
Game/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Wall.cpp.o
.PHONY : Game/Wall.cpp.o

Game/Wall.i: Game/Wall.cpp.i

.PHONY : Game/Wall.i

# target to preprocess a source file
Game/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Wall.cpp.i
.PHONY : Game/Wall.cpp.i

Game/Wall.s: Game/Wall.cpp.s

.PHONY : Game/Wall.s

# target to generate assembly for a file
Game/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Game/Wall.cpp.s
.PHONY : Game/Wall.cpp.s

Irrlicht/IrrLib.o: Irrlicht/IrrLib.cpp.o

.PHONY : Irrlicht/IrrLib.o

# target to build an object file
Irrlicht/IrrLib.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/IrrLib.cpp.o
.PHONY : Irrlicht/IrrLib.cpp.o

Irrlicht/IrrLib.i: Irrlicht/IrrLib.cpp.i

.PHONY : Irrlicht/IrrLib.i

# target to preprocess a source file
Irrlicht/IrrLib.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/IrrLib.cpp.i
.PHONY : Irrlicht/IrrLib.cpp.i

Irrlicht/IrrLib.s: Irrlicht/IrrLib.cpp.s

.PHONY : Irrlicht/IrrLib.s

# target to generate assembly for a file
Irrlicht/IrrLib.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/IrrLib.cpp.s
.PHONY : Irrlicht/IrrLib.cpp.s

Irrlicht/MyEventReceiver.o: Irrlicht/MyEventReceiver.cpp.o

.PHONY : Irrlicht/MyEventReceiver.o

# target to build an object file
Irrlicht/MyEventReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/MyEventReceiver.cpp.o
.PHONY : Irrlicht/MyEventReceiver.cpp.o

Irrlicht/MyEventReceiver.i: Irrlicht/MyEventReceiver.cpp.i

.PHONY : Irrlicht/MyEventReceiver.i

# target to preprocess a source file
Irrlicht/MyEventReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/MyEventReceiver.cpp.i
.PHONY : Irrlicht/MyEventReceiver.cpp.i

Irrlicht/MyEventReceiver.s: Irrlicht/MyEventReceiver.cpp.s

.PHONY : Irrlicht/MyEventReceiver.s

# target to generate assembly for a file
Irrlicht/MyEventReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Irrlicht/MyEventReceiver.cpp.s
.PHONY : Irrlicht/MyEventReceiver.cpp.s

src/Actions.o: src/Actions.cpp.o

.PHONY : src/Actions.o

# target to build an object file
src/Actions.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Actions.cpp.o
.PHONY : src/Actions.cpp.o

src/Actions.i: src/Actions.cpp.i

.PHONY : src/Actions.i

# target to preprocess a source file
src/Actions.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Actions.cpp.i
.PHONY : src/Actions.cpp.i

src/Actions.s: src/Actions.cpp.s

.PHONY : src/Actions.s

# target to generate assembly for a file
src/Actions.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Actions.cpp.s
.PHONY : src/Actions.cpp.s

src/Core.o: src/Core.cpp.o

.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i

.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s

.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/MapGenerator.o: src/MapGenerator.cpp.o

.PHONY : src/MapGenerator.o

# target to build an object file
src/MapGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MapGenerator.cpp.o
.PHONY : src/MapGenerator.cpp.o

src/MapGenerator.i: src/MapGenerator.cpp.i

.PHONY : src/MapGenerator.i

# target to preprocess a source file
src/MapGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MapGenerator.cpp.i
.PHONY : src/MapGenerator.cpp.i

src/MapGenerator.s: src/MapGenerator.cpp.s

.PHONY : src/MapGenerator.s

# target to generate assembly for a file
src/MapGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MapGenerator.cpp.s
.PHONY : src/MapGenerator.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/MenuItem.o: src/MenuItem.cpp.o

.PHONY : src/MenuItem.o

# target to build an object file
src/MenuItem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MenuItem.cpp.o
.PHONY : src/MenuItem.cpp.o

src/MenuItem.i: src/MenuItem.cpp.i

.PHONY : src/MenuItem.i

# target to preprocess a source file
src/MenuItem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MenuItem.cpp.i
.PHONY : src/MenuItem.cpp.i

src/MenuItem.s: src/MenuItem.cpp.s

.PHONY : src/MenuItem.s

# target to generate assembly for a file
src/MenuItem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/MenuItem.cpp.s
.PHONY : src/MenuItem.cpp.s

src/Music.o: src/Music.cpp.o

.PHONY : src/Music.o

# target to build an object file
src/Music.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Music.cpp.o
.PHONY : src/Music.cpp.o

src/Music.i: src/Music.cpp.i

.PHONY : src/Music.i

# target to preprocess a source file
src/Music.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Music.cpp.i
.PHONY : src/Music.cpp.i

src/Music.s: src/Music.cpp.s

.PHONY : src/Music.s

# target to generate assembly for a file
src/Music.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Music.cpp.s
.PHONY : src/Music.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bomberman"
	@echo "... Game/ACube.o"
	@echo "... Game/ACube.i"
	@echo "... Game/ACube.s"
	@echo "... Game/Bomb.o"
	@echo "... Game/Bomb.i"
	@echo "... Game/Bomb.s"
	@echo "... Game/Crate.o"
	@echo "... Game/Crate.i"
	@echo "... Game/Crate.s"
	@echo "... Game/EntityPos.o"
	@echo "... Game/EntityPos.i"
	@echo "... Game/EntityPos.s"
	@echo "... Game/Fire.o"
	@echo "... Game/Fire.i"
	@echo "... Game/Fire.s"
	@echo "... Game/GameCore.o"
	@echo "... Game/GameCore.i"
	@echo "... Game/GameCore.s"
	@echo "... Game/Item.o"
	@echo "... Game/Item.i"
	@echo "... Game/Item.s"
	@echo "... Game/Player.o"
	@echo "... Game/Player.i"
	@echo "... Game/Player.s"
	@echo "... Game/Shield.o"
	@echo "... Game/Shield.i"
	@echo "... Game/Shield.s"
	@echo "... Game/Wall.o"
	@echo "... Game/Wall.i"
	@echo "... Game/Wall.s"
	@echo "... Irrlicht/IrrLib.o"
	@echo "... Irrlicht/IrrLib.i"
	@echo "... Irrlicht/IrrLib.s"
	@echo "... Irrlicht/MyEventReceiver.o"
	@echo "... Irrlicht/MyEventReceiver.i"
	@echo "... Irrlicht/MyEventReceiver.s"
	@echo "... src/Actions.o"
	@echo "... src/Actions.i"
	@echo "... src/Actions.s"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/MapGenerator.o"
	@echo "... src/MapGenerator.i"
	@echo "... src/MapGenerator.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/MenuItem.o"
	@echo "... src/MenuItem.i"
	@echo "... src/MenuItem.s"
	@echo "... src/Music.o"
	@echo "... src/Music.i"
	@echo "... src/Music.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

